spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: 1234
    url: jdbc:postgresql://localhost:5433/clientes
    username: postgres
   rabbitmq:
       host: localhost
       port: 5672
       username: diego
       password: 1234
