spring:
  datasource:
   password: 1234
   username: postgres
   url: jdbc:postgresql://localhost/clientes
  rabbitmq:
       host: localhost
       port: 5672
       username: diego
       password: 1234
